### ISSUE TITLE
"-nic: invalid option" when run QEMU image on ubuntu 18.04

### ISSUE THREAD

**Issue by mingguangZhou** [vectorgrp/sil-kit-adapters-qemu#1]
[  -nic user,hostfwd=tcp::10022-:22,mac=00:11:22:33:44:55  \](https://github.com/vectorgrp/sil-kit-adapters-qemu/blob/210e2d187b81fda646805bc328f13012a50336ce/tools/run-silkit-qemu-demos-guest.sh#L8)
need to be replaced by 
`-netdev user,id=net0,hostfwd=tcp::10022-:22 \
-device e1000,netdev=net0,mac=00:11:22:33:44:55
` to make it work on my ubuntu 18.04

**Comment by SvenMorgenthaler** [comment]
@mingguangZhou: Thanks a lot for the hint. Since version 18.04 of Ubuntu is EOL for more than 1.5 years, we ask for your understanding that we will not take any further action on this issue.

**Comment by VSvenMorgenthaler** [comment]
Ubuntu 18.04 is EOL (see comment above)
